### ISSUE TITLE
Shipping management

### ISSUE THREAD

**Issue by CraziFuzzy** [Glampi42/ONI-Mods#3]
Would it be difficult to bring this interface over to shipping rails as well?  They seem to use the same general mechanism in game, and honestly, I'm spoiled now with pipes and ducts, and i need it for my rails too!

**Comment by Glampi42** [comment]
When I only began to work on this mod I actually planned it to work for all three conduit types: liquid, gas and solid(conveyor). However, as I inspected the game's code and after some testing I figured out, that the conveyor rails work completely different from the pipes. For instance, if you have a long pipe connecting two junctions, then the flow direction of each pipe segment of that pipe goes in the same direction. This is not the case with conveyor rails: they basically start to behave very strange in each situation that is non-linear. Meaning: if there are multiple ways stuff can move in, conveyor rails won't work properly. What this means for my mod is: it is impossible to change flow directions of conveyor rails because they pretty much don't have one; it is not useful to change flow priorities because the rails behave very weird in situations where flow priority could potentially be used; the overlay part(green junctions) is also meaningless because it wouldn't represent the "real" flow directions because of the way rails work. So, as you can see, all aspects of my mod are sadly not appliable on conveyor rails.
